### PR TITLE
Experiment fate

### PR DESCRIPTION
**Pull request by AleksandarFilipov**
Added FATE contract. Test can now specify version of abi and wm.
Contract calls can now specify amounts and deposits

### CODE REVIEW

**Review by tolbrino — DISMISSED** [review]
PR is out of date.

**Comment by AleksandarFilipov** [comment]
Ready for review

**Comment by tolbrino** [comment]
> Ready for review

No, the commit history is off. It includes commits which are already on master.

**Comment by AleksandarFilipov** [comment]
ok now it should be good to go

**Review by velzevur — APPROVED** [review]

**Pull request merged**
